name: new
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - attrs=22.1.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - coverage=6.3.2
  - coveralls=3.3.1
  - cpuonly=2.0
  - cryptography=38.0.1
  - cycler=0.11.0
  - dbus=1.13.18
  - docopt=0.6.2
  - expat=2.4.9
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.4
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nspr=4.33
  - nss=3.74
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openssl=1.1.1s
  - packaging=21.3
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2.2
  - pluggy=1.0.0
  - ply=3.11
  - py=1.11.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - pytest=7.1.2
  - pytest-cov=3.0.0
  - python=3.10.8
  - python-dateutil=2.8.2
  - pytorch=1.13.0
  - pytorch-mutex=1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.40.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - typing_extensions=4.3.0
  - tzdata=2022f
  - urllib3=1.26.12
  - wheel=0.37.1
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - pyqt5-sip==12.11.0
    - pyyaml==6.0
