name: Unit tests for Python 3.7+

on:
  push:
    branches:    
      - unittest
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # remove numba and cupy, as GitHub's GPU runner is not yet available
        # https://github.com/orgs/github/projects/4247/views/1?filterQuery=GPU
        pip install . && pip install matplotlib pytest
    - name: Test with pytest
      run: |
        cd tests
        pytest
